### ISSUE TITLE
After Insert No Return ID value 

### ISSUE THREAD

**Issue by comfreakph** [FransBouma/Massive#213]
After successfully insert there's no return value for ID

Sample Code:
```csharp
public dynamic SaveUser(string name, string email)
{
	dynamic result = new ExpandoObject();
	result.Success = false;
	try
	{
		result.User = this.Insert(new { 
			Name = name, 
			Email = email
		});
		result.Success = true;
		result.Message = "Successfully saved!";
	}
	catch (Exception ex)
	{
		result.Message = ex.Message;
	}
	return result;
}
```

if you look at the SaveUser.User.ID, the value is Null

this was working in the previous versions.

Thanks

**Comment by FransBouma** [comment]
(I took over Massive from Rob, so that's the reason why this reply is so late ;))

Do you happen to have a trigger on the table which is executed on insert which does inserts with identity fields too? In the case of a trigger being present, @@IDENTITY is required, as SCOPE_IDENTITY() then won't cut it.

**Comment by robconery** [comment]
SCOPE_IDENTITY vs. @@IDENTITY is my biggest issue - SQL Server people want SI, CE and lighter versions of SQL don’t support it.



On March 4, 2015 at 5:30:04 PM, Frans Bouma (notifications@github.com) wrote:

(I took over Massive from Rob, so that's the reason why this reply is so late ;))

Do you happen to have a trigger on the table which is executed on insert which does inserts with identity fields too? In the case of a trigger being present, @@IDENTITY is required, as SCOPE_IDENTITY() then won't cut it.

**Comment by FransBouma** [comment]
Good point. CE is phased out though by Microsoft, however people will have to use it still. It might be good to have a compatibility setting, which could also guide paging code for e.g. sql server 2014, newsequentialid() creation etc. and make distinction between trainwreck databases (CE) and normal DBs (normal sqlserver)

**Comment by FransBouma** [comment]
This is fixed in the Refactoring branch in the next commit, for SQL Server.
