### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by FransBouma** [FransBouma/Massive#227]
Currently there are 0.0 tests and that's not that great, as a simple change can make unwanted changes unnoticed. 

I'll try to add some tests on AdventureWorks example DB so there are at least some tests to start with.

**Comment by robconery** [comment]
I’ll dig up the project file I have here and send along what I did...



On March 6, 2015 at 1:24:02 PM, Frans Bouma (notifications@github.com) wrote:

Currently there are 0.0 tests and that's not that great, as a simple change can make unwanted changes unnoticed.

I'll try to add some tests on AdventureWorks example DB so there are at least some tests to start with.

**Comment by robconery** [comment]
Good news: I found it.

Bad news: I deleted all the stuff in the Program.cs file because … I don’t know why. I have the main project in my Win7 VM which I haven’t opened in years - I’ll need to find it…

There are (perhaps) 25 or so tests - not a lot - but it’s better than nothing :).



On March 6, 2015 at 1:24:02 PM, Frans Bouma (notifications@github.com) wrote:

Currently there are 0.0 tests and that's not that great, as a simple change can make unwanted changes unnoticed.

I'll try to add some tests on AdventureWorks example DB so there are at least some tests to start with.

**Comment by FransBouma** [comment]
That would be great indeed :) As long as the tests are there, it's ok, the unit tests are run without program.cs anyway ;)



> Good news: I found it.
> 
> Bad news: I deleted all the stuff in the Program.cs file because … I don’t know why. I have the main
> project in my Win7 VM which I haven’t opened in years - I’ll need to find it…
> 
> There are (perhaps) 25 or so tests - not a lot - but it’s better than nothing :).
> 
> 
>

**Comment by FransBouma** [comment]
Basic 'see if the feature works' tests are now in for SQL Server. As the oracle code is now ported too, I'll add Oracle specific tests for the Oracle specific parts of the code as well. The oracle code in the original massive was seriously buggy though: inserts with sequences NEVER worked (it obtained the new sequence value after the insert, but never inserted the value!) and paging queries too never worked (it used the sql server 2005 paging code... ;)). I hopefully fixed them (will find that out when the tests are added).

**Comment by FransBouma** [comment]
Basic postgresql tests added, as well as oracle tests. So that pretty much covers it, except for sqlite tests.
