### ISSUE TITLE
Include MySQL

### ISSUE THREAD

**Issue by wcervini** [FransBouma/Massive#237]
Any inclusion for MySQL Databases.

**Comment by FransBouma** [comment]
With the new codelayout (see Refactoring branch), Mysql will be easy to add.

**Comment by cbnsndwch** [comment]
Hi! Any news on MySQL support? I've been using an old fork by @alexandernyquist that did have, but it was v1.0. I've moved to v2.0 and am using SQLite for my frontend WPF app (with Massive 2.0) and MySQL for my app's backend/API, so it would be great to know if there are any short term plans for it, since your last response to this thread is dated July 2015.
Cheers!!!

**Comment by FransBouma** [comment]
Not in the coming weeks. First I have to finish LLBLGen Pro v5.0 release, then I'll look at this, so think april/may.

**Comment by punker76** [comment]
@FransBouma Any chance to add this now in 2017?

**Comment by mikebeaton** [comment]
Frans,

As I mentioned I was looking at doing in #302, I've coded MySQL support for Massive.

It's Massive v2.0 support. (I'm still working on totally non-breaking support for most of the other features I mentioned in #302, with good progress, but a v2.0 version of MySQL support can stand alone.)

It passes all 35 read and write tests ported and adapted from SQL Server.

The project structure etc. is exactly as for the other supported DBs.

Is it worth generating a pull request?

Mike

**Comment by mikebeaton** [comment]
@punker76 - if you are interested in trying it, you would be very welcome. It is currently at https://github.com/MikeBeaton/Massive/tree/MySqlSupport .

**Comment by FransBouma** [comment]
Sounds good! One caveat: the MySQL SA ADO.NET provider is GPL licensed. Not a lot of  people are aware of this, but using it (even through massive) will make your own code GPL licensed as well. That might be ridiculous (I think so) but MySQL SA thinks otherwise and will not ignore it if they find out.

So there's another ADO.NET provider, which is free, the DevArt MySQLConnector express (https://www.devart.com/dotconnect/mysql/editions.html) It doesn't do much besides using the DB, but I think it's worth it to mention this in the readme.md. Other than that, looks OK!

**Comment by mikebeaton** [comment]
Great, Frans. Thanks! I'm going off the radar for a couple of days, but after that I will definitely download the other driver and confirm it all works, and update the readme.

What do you make of this: https://www.mysql.com/about/legal/licensing/foss-exception/

**Comment by FransBouma** [comment]
> What do you make of this: https://www.mysql.com/about/legal/licensing/foss-exception/

That's a remark about that a OSS lib using their stuff (e.g. Massive) doesn't have to adjust their license to GPL if they link to a GPL-ed lib (indirectly or directly), but it doesn't lift the license restriction for the software which uses Massive, only for Massive. I find their restrictions absurd, to be honest, as the link is created through .NET itself (through DbProviderFactory), so if anything, _that_ is doing the linking, not Massive, but as they (MySQL SA) is stubborn in this it's best to avoid that debate with them altogether (as they'll simply tell you to become a Valued Added Reseller of their commercial connector licenses!).

**Comment by mikebeaton** [comment]
I've read around the issue and updated the MySQL bullet point in [README.markdown](https://github.com/MikeBeaton/Massive/blob/MySqlSupport/README.markdown) to reflect the very best of my understanding of the issues (whilst also being careful to word things so as to make it clear that anything there is subsidiary to whatever the actual license docs say).

**Comment by mikebeaton** [comment]
The devart driver currently appears to have a bug, not accepting "initial catalog" (http://forums.devart.com/viewtopic.php?f=2&t=35035), but otherwise works fine. The ported tests pass anyway, since the test classes already specify their schema. (To work round that bug, the write test cleanup SP call did need the schema added, i.e. `cmd.CommandText = "massivewritetests.pr_clearAll"`, on Devart only, to replace being able to specify it in the connection string, but I have not commited that change since I figured that this is an issue to be resolved outside Massive.)

**Comment by MikeBeaton** [comment]
(Frans, Just in case you have already started to read, I have just squash-commited another couple of minor changes, including another useful link, into the new MySQL info in my branch's README.markdown.)

**Comment by mikebeaton** [comment]
The Devart 'bug' is resolved with help from the Devart forums. Oracle/MySQL support "initial catalog=" as an alias for "database=", but Devart don't.

I have made a final [commit to change to using "database="](https://github.com/MikeBeaton/Massive/commit/7fde644722e44bad694fc0ff265194a049e4a102) in the tests, since that's obviously preferable for MySQL as it works on both drivers.

**Comment by mikebeaton** [comment]
All (now) 110 (was 75) tests pass on all DBs. All 35 new MySQL tests pass on either MySQL driver (now only changing the provider name and absolutely nothing else!).

**Comment by FransBouma** [comment]
Merged!

**Comment by mikebeaton** [comment]
:-)
