### ISSUE TITLE
Oracle: NUMBER at too great a precision causes error

### ISSUE THREAD

**Issue by FatPanther** [FransBouma/Massive#250]
Oracle NUMBER type offers 38 precision, while .Net Decimal offers 28 precision.  When ODP tries to fetch NUMBER data with too great a precision, an error occurs.  [Details here.](http://docs.oracle.com/html/E10927_01/featSafeType.htm)  

Here's my current band-aid (in RecordToExpando(), replaces `reader.GetValues(values);`):

``` c#
if (reader is Oracle.ManagedDataAccess.Client.OracleDataReader || reader is Oracle.DataAccess.Client.OracleDataReader)
{
    dynamic r = (dynamic)reader;

    for (int i = 0; i < r.FieldCount; i++)
    {
        dynamic value;
        if (r.GetFieldType(i) == typeof(System.Decimal))
        {
            var oType = r.GetOracleDecimal(i);
            value = oType.IsNull ? null : oType.ToDouble();
        }
        else
        {
            value = r.GetValue(i);
        }
        values[i] = value;
    }
}
else
{
    reader.GetValues(values);
}
```

(Double precision works for me, maybe not for others.)  This works as a quick fix, but not sure what direction to go to implement a permanent solution...  The OracleDataAdapter doc linked above discusses the Safe Type Mapping feature, but I wasn't sure what the best way would be to (in Massive) get at the OracleDataAdapter to try it out.

**Comment by FransBouma** [comment]
Yes this is a problem with Oracle. The only problem is that to fix it you need a reference to ODPNET... In LLBLGen Pro I 'solved' it by having a method which is called in case of the overflow exception, so users can override that method and there take the dependency on ODPNET (or other Oracle ADO.NET provider they use) and do the Oracle specific type conversion. It's not ideal though, as it's pretty slow of course, but it otherwise is not possible to fix as the code otherwise needs a reference to ODP.NET as you've noticed. I don't want to take a dependency on ODP.NET in the code, so that's out.

**Comment by FatPanther** [comment]
Frans - understood, & thanks for the description of your solution - might try something similar if I get the chance.  I appreciate your time & all your work on this.

**Comment by FransBouma** [comment]
No problem and thanks for the kind words :)
