### ISSUE TITLE
scaler when where clause is not using '='

### ISSUE THREAD

**Issue by DEllingsworth** [FransBouma/Massive#264]
I'm having trouble with 

var result = ((dynamic)new myData()).max(columns: "col1", where:"col1<100000");

Any suggestions? I'm using some dynamic SQL for now.

**Comment by FransBouma** [comment]
What database type are you using? What does 'trouble' mean exactly? You get an exception? (if so, what's the stacktrace), if SQL is created but it's wrong, what's the SQL?

**Comment by DEllingsworth** [comment]
This code on line 832 assumes '=' in the WHERE predicate. 

`wherePredicates.Add(string.Format(" {0} = {1}", name, this.PrefixParameterName(counter.ToString())));`

I'll try to make a failing test later this week.

**Comment by FransBouma** [comment]
Yeah, that code is broken. Will look into a fix.

**Comment by FransBouma** [comment]
This is the way it is, sadly. How it is now is used by e.g. a method called First() is using this setup. I would never designed it like this but it's a left over from v1 designed by Conery. This also has the side effect that what you want is not supported: you can call a method through the mechanism you're using, but you can't pass where clauses, at least not directly. I tried to fix it, but then First() broke, and it turned out that methods relied on how the TryInvokeMember method behaves. 

This is a limitation, as you can't chain methods together to create queries which aren't doable with the methods provided like All or Find.
